server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: Rahim5089@
    driverClassName: org.postgresql.Driver
logging:
  level:
    org.springframework: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.apache: WARN
